# Generated by Django 5.2.6 on 2025-10-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('mesero', 'Mesero'), ('cajero', 'Cajero')], default='admin', max_length=10),
        ),
    ]
